repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0  # or specific git tag
    hooks:
      - id: shellcheck
        args:
          - "-e"
          - "SC1090"
          - "-e"
          - "SC1091"
  - repo: https://github.com/hadolint/hadolint
    rev: "v2.13.1-beta"
    hooks:
      - id: hadolint-docker
        args:
          - --ignore
          - DL4006
          - --ignore
          - DL3015
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        description: Detects high entropy strings that are likely to be passwords.
        entry: detect-secrets-hook
        language: python
        # for backward compatibility
        files: .*  # all files
        exclude: 'collections/container/kind.yaml'



# ---
# fail_fast: false
# repos:
#   - repo: https://github.com/adrienverge/yamllint
#     rev: v1.27.1
#     hooks:
#       - args:
#           - --config-file
#           - .github/linters/.yamllint.yaml
#         id: yamllint
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.3.0
#     hooks:
#       - id: trailing-whitespace
#       - id: end-of-file-fixer
#       - id: mixed-line-ending
#   - repo: https://github.com/Lucas-C/pre-commit-hooks
#     rev: v1.3.0
#     hooks:
#       - id: remove-crlf
#       - id: remove-tabs
#   - repo: https://github.com/sirosen/texthooks
#     rev: 0.3.1
#     hooks:
#       - id: fix-smartquotes
#   - repo: https://github.com/k8s-at-home/sops-pre-commit
#     rev: v2.1.1
#     hooks:
#       - id: forbid-secrets
