---
roles:
  - src: https://github.com/stuttgart-things/deploy-configure-rke.git
    scm: git
  - src: https://github.com/stuttgart-things/install-configure-powerdns.git
    scm: git
  - src: https://github.com/stuttgart-things/configure-rke-node.git
    scm: git
  - src: https://github.com/stuttgart-things/install-requirements.git
    version: 2025.10.30
    scm: git
  - src: https://github.com/stuttgart-things/create-send-webhook.git
    version: 2024.06.06
    scm: git
  - src: https://github.com/stuttgart-things/install-configure-vault.git
    scm: git
  - src: https://github.com/stuttgart-things/install-configure-nfs.git
    scm: git
  - src: https://github.com/stuttgart-things/manage-filesystem.git
    version: 2024.06.07
    scm: git
  - src: https://github.com/stuttgart-things/download-install-binary.git
    scm: git
    version: 2025.03.27
  - src: https://github.com/stuttgart-things/create-os-user.git
    scm: git
    version: 2024.05.03
  - src: https://github.com/stuttgart-things/install-configure-docker.git
    scm: git
    version: 2025.04.29
  - src: https://github.com/stuttgart-things/install-configure-podman.git
    scm: git
    version: 2024.05.08
  - src: https://github.com/stuttgart-things/manage-proxmox-resources.git
    scm: git
    version: 2024.05.27

collections:
  - name: community.crypto
    version: 3.0.5
  - name: community.general
    version: 12.0.1
  - name: ansible.posix
    version: 2.1.0
  - name: kubernetes.core
    version: 6.2.0
  - name: community.docker
    version: 5.0.4
  - name: community.vmware
    version: 6.1.0
  - name: awx.awx
    version: 24.6.1
  - name: community.hashi_vault
    version: 7.1.0
  - name: ansible.netcommon
    version: 8.2.0
  - name: https://github.com/stuttgart-things/ansible/releases/download/sthings-baseos-25.0.532.tar.gz/sthings-baseos-25.0.532.tar.gz
  - name: https://github.com/stuttgart-things/ansible/releases/download/sthings-container-25.0.535.tar.gz/sthings-container-25.0.535.tar.gz
  - name: https://github.com/stuttgart-things/ansible/releases/download/sthings-rke-25.0.536.tar.gz/sthings-rke-25.0.536.tar.gz
  - name: https://github.com/stuttgart-things/ansible/releases/download/sthings-awx-25.4.837.tar.gz/sthings-awx-25.4.837.tar.gz
