---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      changed_when: no

    - name: Install Python3 and venv
      ansible.builtin.package:
        name:
          - unzip
          - git
        state: present

- name: Create user for golang setup and to test users creation
  ansible.builtin.import_playbook: sthings.baseos.users
  vars:
    profile: {}
    install_addons: false
    users:
      - username: sthings
        name: sthings user
        groups: ['{{ admin_group }}']
        uid: 1005
        home: /home/sthings
        profile: |
          alias ll='ls -ahl'
        generate_ssh_key: false
        enable_ssh_tcp_forwarding: true

- name: Install tools
  ansible.builtin.import_playbook: sthings.container.tools
