---
- name: Converge
  hosts: all
  gather_facts: false

- name: Create baseos job
  ansible.builtin.import_playbook: sthings.awx.baseos
  vars:
    config_path: /tmp/awx-molecule.yaml

- name: Create schedule_baseos job
  ansible.builtin.import_playbook: sthings.awx.schedule_baseos
  vars:
    config_path: /tmp/awx-molecule.yaml

- name: Create hello_awx job
  ansible.builtin.import_playbook: sthings.awx.hello_awx
  vars:
    config_path: /tmp/awx-molecule.yaml

- name: Create render_upload_template job
  ansible.builtin.import_playbook: sthings.awx.render_upload_template
  vars:
    config_path: /tmp/awx-molecule.yaml

- name: Create get_execute_terraform job
  ansible.builtin.import_playbook: sthings.awx.get_execute_terraform
  vars:
    config_path: /tmp/awx-molecule.yaml

- name: Create set_stats job
  ansible.builtin.import_playbook: sthings.awx.set_stats
  vars:
    config_path: /tmp/awx-molecule.yaml

- name: Create create_vm_workflow job
  ansible.builtin.import_playbook: sthings.awx.create_vm_workflow
  vars:
    config_path: /tmp/awx-molecule.yaml
