---
dependency:
  name: galaxy
  enabled: True
  options:
    ignore-certs: True
    requirements-file: requirements.yaml
    ignore-errors: false
    force: True

driver:
  name: docker
platforms:
  - name: ubuntu24
    image: geerlingguy/docker-ubuntu2404-ansible@sha256:129f93fb11c00d2452f541fc926234a2ecf7957d7348fb07832bd0bf6973f503
    command: ${MOLECULE_DOCKER_COMMAND:-""} #sudo apt update -y && sudo apt upgrade -y
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yaml}
  env:
    MY_ENV_VAR: "Set from molecule.yml"

verifier:
  name: ansible

scenario:
  name: awx
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
