---
- name: Converge
  hosts: all
  gather_facts: false

  tasks:
    - name: Check if AWX environment variables are set
      ansible.builtin.set_fact:
        missing_vars: "{{ missing_vars | default([]) + [item] }}"
      when: lookup('env', item, default='') | length == 0
      loop:
        - CONTROLLER_HOST
        - CONTROLLER_USERNAME
        - CONTROLLER_PASSWORD
        - CONTROLLER_VERIFY_SSL
        - VAULT_ROLE_ID
        - VAULT_SECRET_ID
        - VAULT_ADDR

    - name: Fail if required environment variables are missing
      ansible.builtin.fail:
        msg: "Missing required environment variables: {{ missing_vars | join(', ') }}"
      when: missing_vars is defined and missing_vars | length > 0
