---
- name: Create kind cluster
  ansible.builtin.import_playbook: sthings.container.kind
  vars:
    target_host: localhost
    cluster_name: dev
    kind_cluster_name: dev

- name: Deploy AWX
  ansible.builtin.import_playbook: sthings.awx.deploy
  vars:
    target_host: localhost
    cluster_name: dev
    control_plane_ip: "{{ control_plane_ip }}"

- name: Wait for all AWX components to be ready
  ansible.builtin.import_playbook: sthings.awx.check_deployment
  vars:
    target_host: localhost
    cluster_name: dev
    path_to_kubeconfig: /home/sthings/.kube/dev

- name: Add AWX config to molecule host
  hosts: localhost
  become: yes
  tasks:
    - name: Add AWX dev host entry with comment
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED BLOCK - AWX Host Entry"
        block: |
          # AWX dev hostname for local testing
          127.0.1.1 {{ awx_host }}

    - name: Write AWX controller config to file
      copy:
        dest: /tmp/awx-molecule.yaml
        content: | # pragma: allowlist secret
          controller_host: https://{{ awx_host }}
          controller_username: sthings
          controller_password: admin
          vault_approle_id: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
          vault_approle_secret: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
          vault_url: "{{ lookup('env', 'VAULT_ADDR') }}"
          tower_verify_ssl: false
        mode: '0777'
