---
- name: Create kind cluster
  ansible.builtin.import_playbook: sthings.container.kind
  vars:
    target_host: localhost
    cluster_name: dev
    kind_cluster_name: dev

- name: Deploy awx
  ansible.builtin.import_playbook: sthings.awx.deploy
  vars:
    target_host: localhost
    cluster_name: dev
    control_plane_ip: "{{ control_plane_ip }}"

- name: Wait for all AWX components to be ready
  ansible.builtin.import_playbook: sthings.awx.check_deployment
  vars:
    target_host: localhost
    cluster_name: dev
    path_to_kubeconfig: /home/sthings/.kube/dev


  # post_tasks:
  #   - name: Check if awx environment variables are set
  #     ansible.builtin.set_fact:
  #       missing_vars: "{{ missing_vars | default([]) + [item] }}"
  #     when: lookup('env', item, default='') | length == 0
  #     loop:
  #       - CONTROLLER_HOST
  #       - CONTROLLER_USERNAME
  #       - CONTROLLER_PASSWORD
  #       - CONTROLLER_VERIFY_SSL
  #       - VAULT_ROLE_ID
  #       - VAULT_SECRET_ID
  #       - VAULT_ADDR

  #   - name: Fail if required environment variables are missing
  #     ansible.builtin.fail:
  #       msg: "Missing required environment variables: {{ missing_vars | join(', ') }}"
  #     when: missing_vars is defined and missing_vars | length > 0
