---
- name: Converge
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      changed_when: no

    - name: Install Python3 and venv
      ansible.builtin.package:
        name:
          - unzip
          - git
        state: present

- name: Create user for golang setup and to test users creation
  ansible.builtin.import_playbook: sthings.baseos.users
  vars:
    profile: {}
    install_addons: false
    users:
      - username: sthings
        name: sthings user
        groups: ['{{ admin_group }}']
        uid: 1005
        home: /home/sthings
        profile: |
          alias ll='ls -ahl'
        generate_ssh_key: false
        enable_ssh_tcp_forwarding: true

- name: Install binaries
  ansible.builtin.import_playbook: sthings.baseos.binaries

- name: Install pre-commit
  ansible.builtin.import_playbook: sthings.baseos.pre_commit

# - name: Install semantic-release
#   ansible.builtin.import_playbook: sthings.baseos.semantic_release

- name: Install golang
  ansible.builtin.import_playbook: sthings.baseos.golang
  vars:
    install_addons: false

- name: ansible
  ansible.builtin.import_playbook: sthings.baseos.ansible
