---
- name: Install python, virtualenv & ansible
  hosts: all
  become: true
  vars:
    developer: sthings
    bashrc_path: "/home/{{ developer }}/.bashrc"
    developer_user_dir: "/home/{{ developer }}"
    python_modules:
      - name: ansible
        version: 10.4.0
      - name: kubernetes
        version: 31.0.0
      - name: openshift
        version: 0.13.2
      - name: hvac[parser]
        version: 2.3.0
      - name: pyvmomi
        version: 8.0.3.0.1
    sthings_ansible_requirements: https://raw.githubusercontent.com/stuttgart-things/ansible/main/requirements.yaml

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Python3 and venv
      ansible.builtin.package:
        name:
          - python3
          - python3-venv
        state: present

    - name: Create venv for ansible
      ansible.builtin.shell: |
        python3 -m venv ansible-venv
      args:
        chdir: "{{ developer_user_dir }}"
        creates: "{{ developer_user_dir }}/ansible-venv"
      become: yes
      become_user: "{{ developer }}"

    - name: Install pip
      ansible.builtin.shell: |
        . ansible-venv/bin/activate
        pip install --upgrade pip
      args:
        chdir: "{{ developer_user_dir }}"
      become: yes
      become_user: "{{ developer }}"

    - name: Install required Python modules in venv
      ansible.builtin.pip:
        name: "{{ item.name }}=={{ item.version }}"
        virtualenv: "{{ developer_user_dir }}/ansible-venv"
      loop: "{{ python_modules }}"
      become: yes
      become_user: "{{ developer }}"

    - name: Add venv activation to bashrc
      ansible.builtin.lineinfile:
        path: "{{ bashrc_path }}"
        line: 'source {{ developer_user_dir }}/ansible-venv/bin/activate'
        create: yes
        state: present
      become: yes
      become_user: "{{ developer }}"

    - name: Download sthings ansible requirements file from git
      uri:
        url: "{{ sthings_ansible_requirements }}"
        dest: /tmp/requirements.yaml

    - name: Install ansible requirements
      ansible.builtin.shell: |
        . ansible-venv/bin/activate
        ansible --version
        ansible-galaxy install -r /tmp/requirements.yaml -f
      args:
        chdir: "{{ developer_user_dir }}"
      become: yes
      become_user: "{{ developer }}"
