---
- hosts: localhost
  tasks:
    - name: Include vars
      ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"
      when: path_to_vars_file is defined

    - ansible.builtin.add_host:
        name: "{{ groups['initial_master_node'][0] }}"
        groups: initial_master_node

- hosts: initial_master_node
  vars:
    vault_approle_id: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
    vault_approle_secret: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
    vault_url: "{{ lookup('env', 'VAULT_ADDR') }}"
    replace_ip: true
    check_kubeconfig: true
    create_flux_ns: false

    kubeconfig_path: /etc/rancher/k3s/k3s.yaml
    secret_path_kubeconfig: kubeconfigs # pragma: allowlist secret
    cluster_name: test-cluster

  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"
      when: path_to_vars_file is defined

  tasks:
    - name: Fetch kubeconfig local to ansible host
      ansible.builtin.fetch:
        src: "{{ kubeconfig_path }}"
        dest: "{{ kubeconfig_path|basename }}"
        flat: yes
        run_once: true
      become: true

    - name: Add external ip to kubeconfig
      ansible.builtin.replace:
        dest: "{{ kubeconfig_path|basename }}"
        regexp: '127.0.0.1'
        replace: "{{ ansible_default_ipv4.address }}"
      delegate_to: localhost
      when: replace_ip|bool

    - name: Read local kubeconfig file
      ansible.builtin.slurp:
        src: "{{ kubeconfig_path|basename }}"
      register: kubeconfig_file
      delegate_to: localhost

    - name: Write kubeconfig into Vault kv-v2 path
      community.hashi_vault.vault_write:
        url: "{{ vault_url }}"
        auth_method: approle
        role_id: "{{ vault_approle_id }}"
        secret_id: "{{ vault_approle_secret }}"
        path: "{{ secret_path_kubeconfig }}/data/{{ cluster_name }}"
        validate_certs: false
        data:
          data:
            kubeconfig: "{{ kubeconfig_file['content'] | b64decode }}"
      delegate_to: localhost

    - name: Create flux-system namespace
      kubernetes.core.k8s:
        name: flux-system
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ kubeconfig_path|basename }}"
      when: create_flux_ns|bool
      delegate_to: localhost
