---
playbooks:
  - name: deploy_helmfile
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        vars_files:
          - "{{ path | default('.') }}/{{ profile }}.yaml"

        vars:
          kubeconfig_path: ~/.kube/config
          install_bins: true
          kubectl_version: v1.35.0
          k9s_version: 0.50.16
          helmfile_version: 1.2.3
          helm_version: 4.0.4
          ansible_user: sthings

          bin:
            kubectl:
              bin_name: "kubectl"
              bin_version: "{{ kubectl_version }}"
              check_bin_version_before_installing: true
              source_url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
              bin_to_copy: "kubectl"
              to_remove: "kubectl"
              bin_dir: "/usr/local/bin"
              version_cmd: " version --client"
              target_version: "{{ kubectl_version }}"
            helmfile:
              bin_name: helmfile
              bin_version: "{{ helmfile_version }}"
              check_bin_version_before_installing: true
              source_url: "https://github.com/helmfile/helmfile/releases/download/v{{ helmfile_version }}/helmfile_{{ helmfile_version }}_linux_amd64.tar.gz"
              bin_to_copy: helmfile
              to_remove: "helmfile"
              bin_dir: "/usr/bin/helmfile"
              version_cmd: "version"
              target_version: "{{ helmfile_version }}"
            helm:
              bin_name: helm
              bin_version: "{{ helm_version }}"
              check_bin_version_before_installing: true
              source_url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
              bin_to_copy: "linux-amd64/helm"
              to_remove: "helm"
              bin_dir: "/usr/bin/helm"
              version_cmd: "version"
              target_version: "{{ helm_version }}"
            k9s:
              bin_name: k9s
              bin_version: "{{ k9s_version }}"
              check_bin_version_before_installing: true
              source_url: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
              bin_to_copy: "k9s"
              to_remove: "k9s"
              bin_dir: "/usr/bin/k9s"
              version_cmd: "version"
              target_version: "{{ k9s_version }}"

        tasks:
          - name: Download and install helmfile
            ansible.builtin.include_role:
              name: sthings.container.download_install_binary
            when: install_bins|bool

          - name: Override app enabled states from command-line variables
            ansible.builtin.set_fact:
              processed_catalog: >-
                {{ processed_catalog | default([]) +
                   [item | combine({'enabled': lookup('vars', 'enable_' + item.name.replace('-', '_'), default=item.enabled) | bool})] }}
            loop: "{{ app_catalog }}"
            loop_control:
              label: "{{ item.name }}"

          - name: Display processed app states
            ansible.builtin.debug:
              msg: "{{ item.name }}: {{ 'enabled' if item.enabled else 'disabled' }}"
            loop: "{{ processed_catalog }}"
            loop_control:
              label: "{{ item.name }}"

          - name: Build CRD list from enabled apps
            ansible.builtin.set_fact:
              crd_list: "{{ processed_catalog | selectattr('enabled', 'equalto', true) | selectattr('crds', 'defined') | map(attribute='crds') | flatten | unique | list }}"

          - name: Display CRDs to be applied
            ansible.builtin.debug:
              msg: "CRDs to apply: {{ crd_list }}"

          - name: Apply CRDs (server-side apply)
            ansible.builtin.shell: |
              kubectl apply -k {{ item }} \
                --server-side \
                --force-conflicts \
                --kubeconfig {{ kubeconfig_path }}
            become: yes
            become_user: "{{ ansible_user }}"
            loop: "{{ crd_list }}"
            when: crd_list | length > 0

          - name: Build helmfile deployment list from enabled apps
            ansible.builtin.set_fact:
              helmfile_list: "{{ processed_catalog | selectattr('enabled', 'equalto', true) | list }}"

          - name: Validate helmfile deployments
            ansible.builtin.assert:
              that:
                - item.state in ['present', 'absent', 'sync']
              msg: "State must be 'present', 'absent', or 'sync'"
            loop: "{{ helmfile_list }}"
            loop_control:
              label: "{{ item.name }}"

          - name: Apply, Sync, or Destroy Helmfile configurations
            ansible.builtin.shell:
              cmd: |
                helmfile init --force
                {% set state_args = [] %}
                {% if item.state_values is defined %}
                {% for key, value in item.state_values.items() %}
                {% set _ = state_args.append('--state-values-set ' ~ key ~ '=' ~ value|string) %}
                {% endfor %}
                {% endif %}

                {% if item.state == 'present' %}
                helmfile apply -f {{ item.location }} --kubeconfig {{ kubeconfig_path }} {{ state_args | join(' ') }}
                {% elif item.state == 'absent' %}
                helmfile destroy -f {{ item.location }} --kubeconfig {{ kubeconfig_path }} {{ state_args | join(' ') }}
                {% elif item.state == 'sync' %}
                helmfile sync -f {{ item.location }} --kubeconfig {{ kubeconfig_path }} {{ state_args | join(' ') }}
                {% endif %}
            become: yes
            become_user: "{{ ansible_user }}"
            loop: "{{ helmfile_list }}"
            loop_control:
              label: "{{ item.name }} (state: {{ item.state }})"
            register: helmfile_results

          - name: Display helmfile results
            ansible.builtin.debug:
              msg: "{{ item.stdout_lines }}"
            loop: "{{ helmfile_results.results }}"
            loop_control:
              label: "{{ item.item.name }}"
            when: helmfile_results.results is defined

vars:
  - name: catalog
    file: |
      ---
      # APP CATALOG
      # Each app can be overridden at runtime using: -e enable_<app_name>=true/false
      # Note: Hyphens in app names are converted to underscores (e.g., cert-manager → enable_cert_manager)

      app_catalog:
        - name: cilium
          enabled: true
          description: "CNI plugin for Kubernetes"
          crds:
            - https://github.com/stuttgart-things/helm/infra/crds/cilium
          location: "git::https://github.com/stuttgart-things/helm.git@infra/cilium.yaml.gotmpl"
          state: present
          state_values:
            config: kind
            clusterName: "{{ kind_cluster_name }}"
            configureLB: false

        - name: cert-manager
          enabled: true
          description: "X.509 certificate management for Kubernetes"
          crds:
            - https://github.com/stuttgart-things/helm/infra/crds/cert-manager
          location: "git::https://github.com/stuttgart-things/helm.git@infra/cert-manager.yaml.gotmpl"
          state: present
          state_values:
            installCrds: false

        - name: crossplane
          enabled: true
          description: "Infrastructure orchestration platform"
          crds:
            - https://github.com/stuttgart-things/helm/cicd/crds/crossplane
          location: "git::https://github.com/stuttgart-things/helm.git@cicd/crossplane.yaml.gotmpl"
          state: present
          state_values:
            version: 2.1.3
            deployTeraformProvider: false

  - name: usage_examples
    file: |
      ---
      # USAGE EXAMPLES:

      # 1. Use catalog defaults (respects enabled: true/false in catalog)
      ansible-playbook deploy_helmfile.yaml -i inventory.ini

      # 2. Override specific apps from command line
      ansible-playbook deploy_helmfile.yaml -i inventory.ini \
        -e enable_cilium=true \
        -e enable_cert_manager=true \
        -e enable_crossplane=false

      # 3. Enable apps that are disabled by default
      ansible-playbook deploy_helmfile.yaml -i inventory.ini \
        -e enable_argocd=true \
        -e enable_prometheus=true

      # 4. Override with extra vars file
      ansible-playbook deploy_helmfile.yaml -i inventory.ini \
        -e @overrides.yaml

      # overrides.yaml content:
      # enable_cilium: true
      # enable_cert_manager: true
      # enable_crossplane: true
      # enable_argocd: false

      # 5. Combine with other variables
      ansible-playbook deploy_helmfile.yaml -i inventory.ini \
        -e enable_cilium=true \
        -e kind_cluster_name=my-cluster \
        -e profile=dev
