---
playbooks:
  - name: deploy_helmfile
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        vars_files:
          - "{{ path | default('.') }}/{{ profile }}.yaml"

        vars:
          kubeconfig_path: ~/.kube/config
          install_bins: true
          kubectl_version: v1.35.0 # datasource=github-tags depName=kubernetes/kubectl
          k9s_version: 0.50.16 # datasource=github-tags depName=derailed/k9s
          helmfile_version: 1.2.3 # datasource=github-tags depName=helmfile/helmfile
          helm_version: 4.0.4 # datasource=github-tags depName=helm/helm
          ansible_user: sthings

          bin:
            kubectl:
              bin_name: "kubectl"
              bin_version: "{{ kubectl_version }}"
              check_bin_version_before_installing: true
              source_url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
              bin_to_copy: "kubectl"
              to_remove: "kubectl"
              bin_dir: "/usr/local/bin"
              version_cmd: " version --client"
              target_version: "{{ kubectl_version }}"
            helmfile:
              bin_name: helmfile
              bin_version: "{{ helmfile_version }}"
              check_bin_version_before_installing: true
              source_url: "https://github.com/helmfile/helmfile/releases/download/v{{ helmfile_version }}/helmfile_{{ helmfile_version }}_linux_amd64.tar.gz"
              bin_to_copy: helmfile
              to_remove: "helmfile"
              bin_dir: "/usr/bin/helmfile"
              version_cmd: "version"
              target_version: "{{ helmfile_version }}"
            helm:
              bin_name: helm
              bin_version: "{{ helm_version }}"
              check_bin_version_before_installing: true
              source_url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
              bin_to_copy: "linux-amd64/helm"
              to_remove: "helm"
              bin_dir: "/usr/bin/helm"
              version_cmd: "version"
              target_version: "{{ helm_version }}"
            k9s:
              bin_name: k9s
              bin_version: "{{ k9s_version }}"
              check_bin_version_before_installing: true
              source_url: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
              bin_to_copy: "k9s"
              to_remove: "k9s"
              bin_dir: "/usr/bin/k9s"
              version_cmd: "version"
              target_version: "{{ k9s_version }}"

        pre_tasks:
          - name: Include vars
            ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"
            when: path_to_vars_file is defined

        tasks:
          - name: Download and install helmfile
            ansible.builtin.include_role:
              name: sthings.container.download_install_binary
            when: install_bins|bool

          - name: Apply Kustomize configurations (server-side apply)
            ansible.builtin.shell: |
              kubectl apply -k {{ item }} \
                --server-side \
                --force-conflicts \
                --kubeconfig {{ kubeconfig_path }}
            become: yes
            become_user: "{{ ansible_user }}"
            loop: "{{ kustomize_urls }}"
            when: kustomize_urls is defined and kustomize_urls | length > 0

          - name: Validate and process Helmfile deployments
            ansible.builtin.assert:
              that:
                - item.state in ['present', 'absent', 'sync']
              msg: "State must be 'present', 'absent', or 'sync'"
            loop: "{{ helmfile_deployments }}"
            loop_control:
              label: "{{ item.location }}"
            when: helmfile_deployments is defined and helmfile_deployments | length > 0

          - name: Apply, Sync, or Destroy Helmfile configurations
            ansible.builtin.shell:
              cmd: |
                helmfile init --force
                {% set state_args = [] %}
                {% if item.state_values is defined %}
                {% for key, value in item.state_values.items() %}
                {% set _ = state_args.append('--state-values-set ' ~ key ~ '=' ~ value|string) %}
                {% endfor %}
                {% endif %}

                {% if item.state == 'present' %}
                helmfile apply -f {{ item.location }} --kubeconfig {{ kubeconfig_path }} {{ state_args | join(' ') }}
                {% elif item.state == 'absent' %}
                helmfile destroy -f {{ item.location }} --kubeconfig {{ kubeconfig_path }} {{ state_args | join(' ') }}
                {% elif item.state == 'sync' %}
                helmfile sync -f {{ item.location }} --kubeconfig {{ kubeconfig_path }} {{ state_args | join(' ') }}
                {% endif %}
            become: yes
            become_user: "{{ ansible_user }}"
            loop: "{{ helmfile_deployments }}"
            loop_control:
              label: "{{ item.location }} (state: {{ item.state }})"
            when: helmfile_deployments is defined and helmfile_deployments | length > 0

          - name: Display helmfile apply results
            ansible.builtin.debug:
              msg: "{{ item.stdout_lines }}"
            loop: "{{ helmfile_apply_result.results }}"
            loop_control:
              label: "{{ item.item.location }}"
            when: helmfile_apply_result is defined

vars:
  - name: app_catalog
    file: |
      ---
      # add catalog with all available apps and booleans to enable and overwriteable vars

  - name: xplane_helmfile
    file: |
      ---
      kustomize_urls:
        - https://github.com/stuttgart-things/helm/infra/crds/cilium
        - https://github.com/stuttgart-things/helm/infra/crds/cert-manager
        - https://github.com/stuttgart-things/helm/cicd/crds/crossplane

      helmfile_deployments:
        - location: "git::https://github.com/stuttgart-things/helm.git@infra/cilium.yaml.gotmpl"
          state: present  # or absent
          state_values:
            config: kind
            clusterName: "{{ kind_cluster_name}}"
            configureLB: false

        - location: "git::https://github.com/stuttgart-things/helm.git@infra/cert-manager.yaml.gotmpl"
          state: present  # or absent
          state_values:
            installCrds: false

        - location: "git::https://github.com/stuttgart-things/helm.git@cicd/crossplane.yaml.gotmpl"
          state: present  # or absent
          state_values:
            version: 2.1.3
            deployTeraformProvider: false
