---
playbooks:
  - name: deploy_to_k8s
    play: |
      ---
      - hosts: "{{ target_host | default('localhost') }}"
        become: true
        vars:
          tmp_dir: "{{ '~' if ansible_user_id == 'nonroot' else '/tmp' }}"
          local_user: "{{ ansible_user }}"
          become_local_user: true

        vars_files:
          - "{{ path | default('.') }}/{{ profile }}.yaml"
          #- "{{ deployment_vars }}"

        tasks:
          - name: Create pre manifests
            ansible.builtin.include_tasks: manifests.yaml
            loop: "{{ q('ansible.builtin.dict', pre_manifests) }}"
            when: pre_manifests is defined

          - name: Configure and (un)install helm charts
            block:
              - name: Install helm requirements
                ansible.builtin.include_tasks: helm_config.yaml

              - name: Deploy helm chart(s)
                ansible.builtin.include_tasks: helm.yaml
                loop: "{{ q('ansible.builtin.dict', helm_releases) }}"
            when: helm_releases is defined

          - name: Create post manifests
            ansible.builtin.include_tasks: manifests.yaml
            loop: "{{ q('ansible.builtin.dict', post_manifests) }}"
            when: post_manifests is defined

  - name: helm_config
    play: |
      ---
      - name: Add helm chart repositories
        kubernetes.core.helm_repository:
          name: "{{ item.key }}"
          repo_url: "{{ item.value.url }}"
          force_update: true
        loop: "{{ q('ansible.builtin.dict', helm_repositories) }}"
        when: helm_repositories is defined and state == "present"

      - name: Install Helm Diff
        kubernetes.core.helm_plugin:
          plugin_path: "https://github.com/databus23/helm-diff"
          state: present
        when: state == "present"

  - name: helm
    play: |
      ---
      - name: Create helm values on disk
        ansible.builtin.copy:
          content: "{{ item.value.release_values }}" #().0
          dest: "{{ tmp_dir }}/{{ item.key }}-values.yaml.j2"
        delegate_to: 127.0.0.1
        when: state == "present" and item.value.values is defined
        become: "{{ become_local_user }}"
        become_user: "{{ local_user }}"

      - name: Deploy helm charts
        kubernetes.core.helm:
          kubeconfig: "{{ path_to_kubeconfig }}"
          name: "{{ item.key }}"
          chart_ref: "{{ item.value.ref }}"
          chart_version: "{{ item.value.version | default('latest') }}"
          release_namespace: "{{ item.value.namespace }}"
          create_namespace: true
          state: "{{ state | default('present') }}"
          values: "{{ lookup('template', '{{ tmp_dir }}/{{ item.key }}-values.yaml.j2') | from_yaml | default(omit) }}"
          wait: "{{ item.values.wait | default(omit) }}"
        when: helm_releases is defined
        ignore_errors: "{{ item.value.ignore | default(omit) }}"

      - name: Wait until pods are running
        kubernetes.core.k8s_info:
          kubeconfig: "{{ path_to_kubeconfig }}"
          api_version: v1
          kind: Pod
          namespace: "{{ item.value.namespace }}"
        register: pod_list
        retries: "{{ item.value.wait_retries | default(10) }}"
        delay: "{{ item.value.wait_delay | default(5) }}"
        until: (pod_list is defined) and
               (pod_list.resources | default([]) | length > 0) and
               ("Running" in (pod_list | json_query('resources[*].status.phase')))
        when: state == "present" and item.value.namespace is defined

      - name: Wait for webhooks beeing ready
        ansible.builtin.wait_for:
          timeout: "{{ webhook_wait | default(0) }}"

      - name: Check for CRDs
        ansible.builtin.command: >
          kubectl get crd "{{ item }}" --no-headers -o name
        environment:
          KUBECONFIG: "{{ path_to_kubeconfig }}"
        register: crd_check
        until: crd_check.rc == 0
        retries: "{{ max_retries | default (25) }}"
        delay: "{{ delay_seconds | default (5) }}"
        ignore_errors: true
        loop: "{{ crd_checks }}"
        changed_when: false
        when: crd_checks is defined

  - name: manifests
    play: |
      ---
      - name: Create template on disk
        ansible.builtin.copy:
          content: "{{ item.value }}"
          dest: "/tmp/{{ item.key }}.yaml.j2"
        delegate_to: 127.0.0.1
        become: "{{ become_local_user }}"
        become_user: "{{ local_user }}"
        when: state == "present"

      - name: Deploy additional manifests
        kubernetes.core.k8s:
          kubeconfig: "{{ path_to_kubeconfig }}"
          state: "{{ state | default('present') }}"
          definition: "{{ lookup('template', '/tmp/{{ item.key }}.yaml.j2') | from_yaml }}"

  - name: send_events_homerun
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        gather_facts: false
        vars:
          # Use plain defaults to avoid recursive templating
          count_messages: 5
          delay: 5
          homerun_address: "{{ lookup('env', 'HOMERUN_ADDRESS') | default('https://homerun.demo-infra.whatever.de/generic') }}"
          homerun_token: "{{ lookup('env', 'HOMERUN_TOKEN') | default('IhrGeheimerToken') }}"
          systems: ["github", "gitlab"]
          titles: ["System Alert", "System Incident", "Incident"]
          messages: ["Memory usage is high", "CPU usage is high", "Memory and CPU usage is high"]
          severities: ["INFO", "ERROR", "WARNING"]
          authors: ["bibi", "gude", "andreu", "qolf", "pat"]
          artifacts: ["image-1.23.tar.gz", "test.tar.gz", "report.json", "result.txt"]
          tags: ["usage,alert", "cpu", "cpu,usage,alert", "memory,usage,alert", "monitoring,usage,alert,memory"]
          domains: ["example.com", "test.com", "mail.com", "demo.com"]
        tasks:
          - name: Send random messages to Homerun app
            uri:
              url: "{{ homerun_address }}"
              method: POST
              headers:
                Content-Type: "application/json"
                X-Auth-Token: "{{ homerun_token }}"
              body_format: json
              validate_certs: no
              body: >
                {{
                  {
                    "title": (titles | random),
                    "message": (messages | random),
                    "severity": (severities | random),
                    "author": (authors | random),
                    "timestamp": "%04d-%02d-%02dT%02d:%02d:%02dZ" | format(2024 + (range(0,10)|random), (range(1,13)|random), (range(1,29)|random), (range(0,24)|random), (range(0,60)|random), (range(0,60)|random)),
                    "system": (systems | random),
                    "tags": (tags | random),
                    "assigneeaddress": (lookup('password', '/dev/null chars=ascii_letters,digits length=8')) ~ '@' ~ (domains | random),
                    "assigneename": (authors | random),
                    "artifacts": (artifacts | random),
                    "url": "http://" ~ (lookup('password', '/dev/null chars=ascii_letters,digits length=6')) ~ '.' ~ (domains | random) ~ '/' ~ (lookup('password', '/dev/null chars=ascii_letters,digits length=10'))
                  }
                }}
            register: response
            loop: "{{ range(1, count_messages + 1) | list }}"
            loop_control:
              index_var: idx
            retries: 3
            delay: "{{ delay }}"
            until: response.status == 200

  - name: provision_edge
    play: | # pragma: allowlist secret
      - name: Create kind-cluster
        ansible.builtin.import_playbook: sthings.container.kind
        vars:
          kind_cluster_name: dev
          deployment_vars: Nil
          ansible_user: sthings
          count_worker_nodes: 3
          count_controlplane_nodes: 1
          kubectl_version: 1.34.0
          kind_version: 0.30.0
          enable_ingress_ports: true
          enable_host_paths: true
          provision_cluster: true
          docker_install_compose: true
          install_kind: true
          path_to_kubeconfig: ~/.kube/test
        when: create_kind_cluster is defined and create_kind_cluster | bool

      #- name: Create k3s-cluster
      #  ansible.builtin.import_playbook: sthings.container.k3s
      #  vars:
      #    k3s_cluster_name: dev
      #    deployment_vars: Nil
      #    ansible_user: sthings
      #    kubectl_version: 1.34.0
      #    path_kubeconfig: "/home/{{ ansible_user }}/.kube/{{ k3s_cluster_name }}"
      #  when: create_k3s_cluster is defined and create_k3s_cluster | bool

      - name: GUI - Deploy Headlamp
        ansible.builtin.import_playbook: sthings.container.deploy_to_k8s
        vars:
          deployment_namespace: kube-system
          headlamp_version: 0.33.0
          path_to_kubeconfig: ~/.kube/test
          domain: example.com
          issuer_name: selfsigned
          create_cert_resource: false
          issuer_annotation: ClusterIssuer
          profile: headlamp
          ansible_user: sthings

      - name: Monitoring - Deploy Loki
        ansible.builtin.import_playbook: sthings.container.deploy_to_k8s
        vars:
          deployment_namespace: observability
          loki_version: 6.31.0
          path_to_kubeconfig: ~/.kube/test
          path: ~/.ansible/collections/ansible_collections/sthings/container/playbooks/vars
          profile: loki
          state: present
          ansible_user: sthings

      - name: Monitoring - Deploy Promtail
        ansible.builtin.import_playbook: sthings.container.deploy_to_k8s
        vars:
          deployment_namespace: observability
          promtail_version: 6.17.0
          lokiServiceName: loki
          lokiNamespace: observability
          path_to_kubeconfig: ~/.kube/test
          path: ~/.ansible/collections/ansible_collections/sthings/container/playbooks/vars
          profile: promtail
          state: present
          ansible_user: sthings

      - name: Monitoring - Deploy Grafana
        ansible.builtin.import_playbook: sthings.container.deploy_to_k8s
        vars:
          deployment_namespace: observability
          grafana_version: 7.3.9
          hostname: grafana
          domain: example.com
          path_to_kubeconfig: ~/.kube/test
          issuer_name: selfsigned
          create_cert_resource: false
          ingress_enabled: true
          path: ~/.ansible/collections/ansible_collections/sthings/container/playbooks/vars
          profile: grafana
          state: present
          ansible_user: sthings

      - name: Homerun - Deploy Base-Stack
        ansible.builtin.import_playbook: sthings.container.deploy_to_k8s
        vars:
          deployment_namespace: homerun
          homerun_chart_version: 'v0.2.1'
          genericPitcherEnabled: true
          textCatcherEnabled: true
          genericPitcherDomain: demo-infra.example.com
          redisStackServiceName: redis-stack-headless
          redisStackPassword: example-password
          redisStackServiceType: ClusterIP
          redisStackStorageClass: standard
          redisStackVersion: '7.2.0-v18 #6.2.6-v9'
          genericPitcherToken: example-token
          issuer_annotation: ClusterIssuer
          path_to_kubeconfig: ~/.kube/test
          path: ~/.ansible/collections/ansible_collections/sthings/container/playbooks/vars
          profile: homerun-base-stack
          state: present
          ansible_user: sthings
