---
playbooks:
  - name: kind
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        become: true
        pre_tasks:
          - name: Include vars
            ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"
            when: path_to_vars_file is defined

        vars:
          ansible_user: sthings
          kind_cluster_name: dev
          path_to_kubeconfig: "/home/{{ ansible_user }}/.kube/{{ kind_cluster_name }}"
          kind_version: 0.34.0 # datasource=github-tags depName=kubernetes-sigs/kind
          kubectl_version: 1.35.0 # datasource=github-tags depName=kubernetes/kubectl
          count_worker_nodes: 3
          count_controlplane_nodes: 1
          enable_ingress_ports: true
          enable_host_paths: true
          provision_cluster: true
          docker_install_compose: true
          install_kind: true
          create_kind_cluster: true

        roles:
          - role: sthings.container.install_configure_docker

        post_tasks:
          - name: Set stats for deployment
            set_fact:
              path_to_kubeconfig: "{{ path_to_kubeconfig }}"
              kind_cluster_name: "{{ kind_cluster_name }}"
              state: present

      - name: Deploy cilium on dev kind cluster
        import_playbook: sthings.container.deploy_to_k8s
        vars:
          profile: cilium-kind
          target_host: all
          cluster_name: "{{ kind_cluster_name }}"
          kind_cluster_name: "{{ kind_cluster_name }}"
          state: "{{ state }}"
          path_to_kubeconfig: "{{ path_to_kubeconfig }}"
        when: provision_cluster is defined and provision_cluster|bool

      - name: Deploy cert-manager on dev kind cluster
        import_playbook: sthings.container.deploy_to_k8s
        vars:
          profile: cert-manager-kind
          state: "{{ state }}"
          path_to_kubeconfig: "{{ path_to_kubeconfig }}"
          target_host: all
          cluster_name: "{{ kind_cluster_name }}"
        when: provision_cluster is defined and provision_cluster|bool

      - name: Deploy ingress-nginx on dev kind cluster
        import_playbook: sthings.container.deploy_to_k8s
        vars:
          profile: ingress-nginx-kind
          path_to_kubeconfig: "{{ path_to_kubeconfig }}"
          target_host: all
          cluster_name: "{{ kind_cluster_name }}"
          state: "{{ state }}"
        when: provision_cluster is defined and provision_cluster|bool

      - name: Set fact Controlplane IP
        import_playbook: sthings.container.get_controlplane_ip
        vars:
          kind_cluster_name: "{{ kind_cluster_name }}"
          ansible_user: sthings
        when: provision_cluster is defined and provision_cluster|bool

  - name: get_controlplane_ip
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        become: true
        vars:
          kind_cluster_name: dev
          ansible_user: sthings

        tasks:
          - name: Get control plane node name
            command: kubectl get nodes --kubeconfig /home/{{ ansible_user }}/.kube/{{ kind_cluster_name }} -o json
            register: nodes_json

          - name: Parse control plane node name
            shell: echo '{{ nodes_json.stdout }}' | jq -r '.items[] | select(.metadata.labels["node-role.kubernetes.io/control-plane"]) | .metadata.name'
            register: control_plane_node

          - name: Get control plane IP
            command: kubectl get node {{ control_plane_node.stdout }} --kubeconfig /home/{{ ansible_user }}/.kube/{{ kind_cluster_name }} -o json
            register: node_json

          - name: Parse control plane IP
            shell: echo '{{ node_json.stdout }}' | jq -r '.status.addresses[] | select(.type=="InternalIP") | .address'
            register: control_plane_ip

          - name: Set control plane IP fact
            set_fact:
              control_plane_ip: "{{ control_plane_ip.stdout }}"

  - name: kind_xplane
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        become: true

        pre_tasks:
          - name: Include vars
            ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"
            when: path_to_vars_file is defined

        vars:
          docker_install_compose: true
          install_kind: true
          create_kind_cluster: true
          ansible_user: sthings

          kind_cluster_name: xplane
          kind_api_port: 6443

          count_worker_nodes: 2
          count_controlplane_nodes: 1

          custom_control_plane_ports:
            - containerPort: "{{ port1 | default(range(34000, 36001) | random) }}"
              hostPort: "{{ port1 | default(range(34000, 36001) | random) }}"
              protocol: TCP
            - containerPort: "{{ port2 | default(range(34000, 36001) | random) }}"
              hostPort: "{{ port2 | default(range(34000, 36001) | random) }}"
              protocol: TCP

          api_server_address: "{{ ansible_default_ipv4.address }}"
          api_server_port: 33846
          generate_api_server_port: false

          set_inotify: true
          install_kind_bins: true
          # Worker Node Specific Mounts
          worker_node_mounts:
            0:  # First worker (index 0)
              - hostPath: /mnt/xplane-1
                containerPath: /data
            1:  # Second worker (index 1)
              - hostPath: /mnt/xplane-2
                containerPath: /data

          rebuild_kind_cluster: true

          disableDefaultCNI: true
          kubeProxyMode: "none"

          # Feature Flags
          enable_ingress_ports: false
          enable_host_paths: true

          kustomize_urls:
            - https://github.com/stuttgart-things/helm/infra/crds/cilium
            - https://github.com/stuttgart-things/helm/infra/crds/cert-manager
            #- https://github.com/stuttgart-things/helm/cicd/crds/crossplane

          helmfile_deployments:
            - location: "git::https://github.com/stuttgart-things/helm.git@infra/cilium.yaml.gotmpl"
              state: "{{ deploy_cilium | default('present') }}"
              state_values:
                config: kind
                clusterName: "{{ kind_cluster_name}}"
                configureLB: false

            - location: "git::https://github.com/stuttgart-things/helm.git@infra/cert-manager.yaml.gotmpl"
              state: "{{ deploy_cert_manager | default('present') }}"
              state_values:
                installCrds: false

            # - location: "git::https://github.com/stuttgart-things/helm.git@cicd/crossplane.yaml.gotmpl"
            #   state: "{{ deploy_crossplane | default('present') }}"
            #   state_values:
            #     version: 2.1.3
            #     deployTeraformProvider: false
            #     deployFunctions: false
            #     deployConfigurations: false

          # manifest_urls:
          #   - https://raw.githubusercontent.com/stuttgart-things/crossplane/refs/heads/main/packages/functions/function-auto-ready.yaml
          #   - https://raw.githubusercontent.com/stuttgart-things/crossplane/refs/heads/main/packages/functions/function-go-templating.yaml
          #   - https://raw.githubusercontent.com/stuttgart-things/crossplane/refs/heads/main/packages/functions/function-kcl.yaml
          #   - https://raw.githubusercontent.com/stuttgart-things/crossplane/refs/heads/main/packages/functions/function-patch-and-transform.yaml

        roles:
          - role: sthings.container.install_configure_docker
