---
playbooks:
  - name: helm
    play: |
      ---
      - name: Create values on disk
        ansible.builtin.copy:
          content: "{{ item.value.release_values }}" #().0
          dest: "/tmp/{{ item.key }}-values.yaml.j2"
        when: state == "present" and item.value.values is defined

      - name: Deploy helm charts
        kubernetes.core.helm:
          kubeconfig: "{{ path_to_kubeconfig }}"
          name: "{{ item.key }}"
          chart_ref: "{{ item.value.ref }}"
          chart_version: "{{ item.value.version | default('latest') }}"
          release_namespace: "{{ item.value.namespace }}"
          create_namespace: true
          state: "{{ state | default('present') }}"
          values: "{{ lookup('template', '/tmp/{{ item.key }}-values.yaml.j2') | from_yaml | default(omit) }}"
          wait: "{{ item.values.wait | default(omit) }}"
        when: helm_releases is defined
        ignore_errors: "{{ item.value.ignore | default(omit) }}"

      - name: Wait until pods are running
        kubernetes.core.k8s_info:
          kubeconfig: "{{ path_to_kubeconfig }}"
          api_version: v1
          kind: Pod
          namespace: "{{ item.value.namespace }}"
          wait_sleep: 30
          wait_timeout: 360
        register: pod_list
        retries: "{{ item.values.wait_retries | default(15) }}"
        delay: "{{ item.values.wait_delay | default(30) }}"
        until: pod_list|json_query('resources[*].status.phase')|unique == ["Running"]
        when: state == "present" and item.value.values is defined

      - name: Wait for webhooks beeing ready
        ansible.builtin.wait_for:
          timeout: "{{ webhook_wait | default(0) }}"
