---
playbooks:
  - name: binaries
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        become: true
        vars:
          download_dir: "/tmp/downloads"

        vars_files:
          - "{{ path | default('.') }}/{{ profile | default('binaries') }}.yaml"
        roles:
          - role: sthings.baseos.download_install_binary

  - name: brew
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        become: true
        vars:
          ansible_user: sthings
          required_packages:
            - build-essential
            - procps
            - curl
            - file
            - git

        tasks:
          - name: Install required packages
            ansible.builtin.apt:
              name: "{{ required_packages }}"
              state: present
              update_cache: yes

          - name: Install Homebrew
            ansible.builtin.shell: |
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              echo >> /home/{{ ansible_user }}/.bashrc
              echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/{{ ansible_user }}/.bashrc
              eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            environment:
              NONINTERACTIVE: 1
            become: false  # Run as current user, not root

  - name: vhs
    play: |
      ---
      - name: Deploy VHS with required dependencies
        hosts: "{{ target_host | default('all') }}"
        become: yes

        vars:
          vhs_version: 0.10.0 # datasource=github-tags depName=charmbracelet/vhs
          bin:
            vhs:
              bin_name: vhs
              bin_version: "{{ vhs_version }}"
              check_bin_version_before_installing: true
              source_url: "https://github.com/charmbracelet/vhs/releases/download/v{{ vhs_version }}/vhs_{{ vhs_version }}_Linux_x86_64.tar.gz"
              bin_to_copy: "vhs_{{ vhs_version }}_Linux_x86_64"
              to_remove: ""
              bin_dir: "/usr/bin/vhs"
              version_cmd: "version"
              target_version: "{{ vhs_version }}"

          chrome_download_url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
          chrome_deb_path: "/tmp/google-chrome-stable_current_amd64.deb"
          system_dependencies:
            - libatk1.0-0
            - libatk-bridge2.0-0
            - libcups2
            - libdrm2
            - libxkbcommon0
            - libxcomposite1
            - libxdamage1
            - libxrandr2
            - libgbm1
            - libpango-1.0-0
            - libgtk-3-0
            - libasound2t64
            - libnss3
            - libxss1
            - libatspi2.0-0
            - fonts-liberation
            - libpangocairo-1.0-0

        roles:
          - role: sthings.baseos.download_install_binary

        pre_tasks:
          - name: Update apt package cache
            ansible.builtin.apt:
              update_cache: yes

          - name: Install required system dependencies
            ansible.builtin.apt:
              name: "{{ system_dependencies }}"
              state: present

          - name: Download Google Chrome
            ansible.builtin.get_url:
              url: "{{ chrome_download_url }}"
              dest: "{{ chrome_deb_path }}"

          - name: Install Google Chrome
            ansible.builtin.apt:
              deb: "{{ chrome_deb_path }}"

          - name: Clean up Chrome installer
            ansible.builtin.file:
              path: "{{ chrome_deb_path }}"
              state: absent

vars:
  - name: binaries
    file: |
      ---
      gum_version: 0.16.2 # datasource=github-tags depName=charmbracelet/gum
      gh_version: 2.86.0 # datasource=github-tags depName=cli/cli
      task_version: 3.48.0 # datasource=github-tags depName=go-task/task
      hugo_version: 0.155.2 # datasource=github-tags depName=gohugoio/hugo
      terraform_version: 1.14.4 # datasource=custom.hashicorp
      packer_version: 1.14.3 # datasource=custom.hashicorp
      yq_version: 4.52.2 # datasource=github-tags depName=mikefarah/yq
      jq_version: 1.7.1 # datasource=github-tags depName=jqlang/jq
      machineshop_version: 2.11.0 # datasource=github-tags depName=stuttgart-things/machineshop
      mc_version: RELEASE.2025-04-08T15-39-49Z #
      crossplane_version: 1.20.4 # datasource=github-tags depName=crossplane/crossplane
      sops_version: 3.11.0 # datasource=github-tags depName=getsops/sops

      bin:
        sops:
          bin_name: sops
          bin_version: "{{ sops_version }}"
          check_bin_version_before_installing: true
          source_url: "https://github.com/getsops/sops/releases/download/v{{ sops_version }}/sops-v{{ sops_version }}.linux.amd64"
          bin_to_copy: "sops-v{{ sops_version }}.linux.amd64"
          to_remove: ""
          bin_dir: "/usr/bin/sops"
          version_cmd: "version"
          target_version: "{{ sops_version }}"
        crossplane:
          bin_name: crossplane
          bin_version: "{{ crossplane_version }}"
          check_bin_version_before_installing: true
          source_url: "https://releases.crossplane.io/stable/v{{ crossplane_version }}/bin/linux_amd64/crank"
          bin_to_copy: crank
          to_remove: ""
          bin_dir: "/usr/bin"
          version_cmd: "version"
          target_version: "{{ crossplane_version }}"
        gum:
          bin_name: gum
          bin_version: "{{ gum_version }}"
          check_bin_version_before_installing: true
          source_url: "https://github.com/charmbracelet/gum/releases/download/v{{ gum_version }}/gum_{{ gum_version }}_Linux_x86_64.tar.gz"
          bin_to_copy: gum_{{ gum_version }}_Linux_x86_64/gum
          to_remove: gum_{{ gum_version }}_Linux_x86_64.tar.gz
          bin_dir: "/usr/local/bin"
          version_cmd: "-- version"
          target_version: "{{ gum_version }}"
        gh:
          bin_name: gh
          bin_version: "{{ gh_version }}"
          check_bin_version_before_installing: true
          source_url: "https://github.com/cli/cli/releases/download/v{{ gh_version }}/gh_{{ gh_version }}_linux_amd64.tar.gz"
          bin_to_copy: gh_{{ gh_version }}_linux_amd64/bin/gh
          to_remove: gh_{{ gh_version }}_linux_amd64.tar.gz
          bin_dir: "/usr/local/bin"
          version_cmd: "-- version"
          target_version: "{{ gh_version }}"
        task:
          bin_name: task
          bin_version: "{{ task_version }}"
          check_bin_version_before_installing: true
          source_url: "https://github.com/go-task/task/releases/download/v{{ task_version }}/task_linux_amd64.tar.gz"
          bin_to_copy: task
          to_remove: task_linux_amd64.tar.gz
          bin_dir: "/usr/local/bin"
          version_cmd: "-- version"
          target_version: "{{ task_version }}"
        hugo:
          bin_name: hugo
          bin_version: "v{{ hugo_version }}"
          check_bin_version_before_installing: true
          source_url: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_{{ hugo_version }}_linux-amd64.tar.gz"
          bin_to_copy: "hugo"
          to_remove: "hugo"
          bin_dir: "/usr/local/bin"
          version_cmd: " --version"
          target_version: v{{ hugo_version }}
        terraform:
          bin_name: "terraform"
          bin_version: "{{ terraform_version }}"
          check_bin_version_before_installing: true
          source_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
          bin_to_copy: "terraform"
          to_remove: "terraform"
          bin_dir: "/usr/local/bin"
          version_cmd: " --version"
          target_version: "{{ terraform_version }}"
        packer:
          bin_name: "packer"
          bin_version: "v{{ packer_version }}"
          check_bin_version_before_installing: true
          source_url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
          bin_to_copy: "packer"
          to_remove: "packer"
          bin_dir: "/usr/local/bin"
          version_cmd: " --version"
          target_version: v{{ packer_version }}
          #md5_checksum: "374f22185f1f8cb25bc53187a2154ef0"
        jq:
          bin_name: jq
          bin_version: "v{{ jq_version }}"
          check_bin_version_before_installing: true
          source_url: "https://github.com/jqlang/jq/releases/download/jq-{{ jq_version }}/jq-linux-amd64"
          bin_to_copy: jq-linux-amd64
          to_remove: ""
          bin_dir: "/usr/bin/jq"
          version_cmd: " version"
          target_version: "v{{ jq_version }}"
        yq:
          bin_name: yq
          bin_version: "v{{ yq_version }}"
          check_bin_version_before_installing: true
          source_url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_version }}/yq_linux_amd64.tar.gz"
          bin_to_copy: yq_linux_amd64
          to_remove: ""
          bin_dir: "/usr/bin/yq"
          version_cmd: " version"
          target_version: "v{{ yq_version }}"
        machineshop:
          bin_name: machineshop
          bin_version: "v{{ machineshop_version }}"
          check_bin_version_before_installing: true
          source_url: https://github.com/stuttgart-things/machineshop/releases/download/v{{ machineshop_version }}/machineshop_Linux_x86_64.tar.gz
          bin_to_copy: machineshop
          to_remove: ""
          bin_dir: "/usr/bin"
          version_cmd: " version"
          target_version: "v{{ machineshop_version }}"
        minio:
          bin_name: mc
          bin_version: "{{ mc_version }}"
          check_bin_version_before_installing: true
          source_url: https://github.com/minio/mc/archive/refs/tags/{{ mc_version }}.zip
          bin_to_copy: mc-{{ mc_version }}
          to_remove: ""
          bin_dir: "/usr/bin"
          version_cmd: " version"
          target_version: "{{ mc_version }}"
