---
playbooks:
  - name: prepare_env
    play: |
      ---
      - hosts: localhost
        become: false
        vars:
          home_dir: "{{ lookup('env','HOME') }}"
          targets_list: "{{ targets.split(';') }}"
          vault_approle_id: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
          vault_approle_secret: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
          vault_url: "{{ lookup('env', 'VAULT_ADDR') }}"
          ssh_key: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=ssh/data/sthings:privateKey validate_certs=false auth_method=approle role_id={{ vault_approle_id }} secret_id={{ vault_approle_secret }} url={{ vault_url }}') }}" # pragma: allowlist secret

        pre_tasks:
          - name: Include vars
            ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"

        tasks:
          - name: Create hosts
            ansible.builtin.set_fact:
              target_hosts: "{{ targets_list | join('\n') }}"
            when: inventory_groups is not defined
            ignore_errors: true

          - name: Write vars on inv file
            ansible.builtin.blockinfile:
              path: "{{ inv_path }}"
              block: |
                [all]
                {{ target_hosts }}
            when: inventory_groups is not defined
            ignore_errors: true

          - name: Append lines to the end of the file
            ansible.builtin.blockinfile:
              path: "{{ inv_path }}"
              block: |
                [all:vars]
                ansible_user=sthings
                host_key_checking=false
              insertafter: EOF
            when: inventory_groups is not defined
            ignore_errors: false

          - ansible.builtin.set_fact:
              inventory_file: |
                {% for host_groups in inventory_groups.keys() %}
                {% for group in inventory_groups[host_groups].keys() %}
                [{{ group }}]
                {% for host in inventory_groups[host_groups][group] %}
                {{ host }}
                {% endfor %}
                {% endfor %}
                {% endfor %}
                [all:vars]
                ansible_user=sthings
                host_key_checking=false
            when: inventory_groups is defined

          - ansible.builtin.debug:
              var: inventory_file
            when: inventory_groups is defined

          - ansible.builtin.copy:
              content: "{{ inventory_file }}"
              dest: "{{ inv_path }}"
            when: inventory_groups is defined

          - name: Creating ssh directory
            ansible.builtin.file:
              path: "{{ home_dir }}/.ssh/"
              state: directory

          - name: Creating ssh private key file
            ansible.builtin.copy:
              dest: "{{ home_dir }}/.ssh/id_rsa"
              content: "{{ ssh_key | b64decode }}"
              mode: '0600'

          - name: Show inventory
            ansible.builtin.debug: msg="{{ lookup('file', inv_path) }}"

          - name: Refresh inventory
            ansible.builtin.meta: refresh_inventory

          - name: "Pause for {{ pause_time | default(1) }} minutes for machines to be build"
            ansible.builtin.pause:
              minutes: "{{ pause_time | default(1) }}"
            when: pause_time is defined

          - name: "Wait for SSH (delay: {{ delay_time | default(1) }})"
            ansible.builtin.wait_for:
              host: "{{ item }}"
              port: 22
              delay: "{{ delay_time | default(1) }}"
              timeout: 1200
              sleep: 10
            with_items:
              - "{{ groups['all'] }}"

  - name: setup
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        become: true
        gather_facts: true

        vars:
          manage_filesystem: true
          update_packages: true
          install_requirements: true
          install_motd: true
          reboot_all: false
          username: sthings
          lvm_home_sizing: "15%"
          lvm_root_sizing: "35%"
          lvm_var_sizing: "50%"
          send_to_homerun: false
          python_modules:
            - name: kubernetes

          # HOMERUN
          address: "https://homerun.homerun-dev.sthings-vsphere.labul.sva.de/generic"
          auth_token: "IhrGeheimerToken"
          event_title: "BaseOS Setup executed"
          event_message: "BaseOS Setup executed on {{ ansible_fqdn }}"
          event_severity: "INFO"
          event_author: "{{ ansible_user_id }}"
          event_timestamp: "{{ ansible_date_time.date }}"
          event_system: "ansible"
          event_tags: "ansible,baseos"
          event_assignee_address: "patrick.hermann@sva.de"
          event_assignee_name: "patrick.hermann"
          event_artifacts: "vm: {{ ansible_fqdn }}"
          event_url: unset

          vault_instances:
            - https://vault.tiab.labda.sva.de:8200
            # - https://vault.labul.sva.de:8200
            # - https://vault-vsphere.labul.sva.de:8200
            - https://vault-vsphere.tiab.labda.sva.de:8200

        roles:
          - role: sthings.baseos.manage_filesystem
            when: manage_filesystem|bool

          - role: sthings.baseos.install_requirements
            when: install_requirements|bool

        pre_tasks:
          - name: Include vars
            ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"
            when: path_to_vars_file is defined

          - ansible.builtin.reboot:
            when: reboot_all|bool

        tasks:
          - name: Install vault ca certificate to local system from multiple instances
            ansible.builtin.include_role:
              name: sthings.baseos.install_configure_vault
              tasks_from: install-ca-auth
            vars:
              vault_url: "{{ vault_instance }}"
            loop: "{{ vault_instances }}"
            loop_control:
              loop_var: vault_instance
            when: vault_instances is defined

          - name: Send event to homerun if enabled
            block:
              - name: Send event notification to homerun
                ansible.builtin.uri:
                  url: "{{ address }}"
                  method: POST
                  headers:
                    Content-Type: "application/json"
                    X-Auth-Token: "{{ auth_token }}"
                  body: >
                    {
                      "title": "{{ event_title }}",
                      "message": "{{ event_message }}",
                      "severity": "{{ event_severity }}",
                      "author": "{{ event_author }}",
                      "timestamp": "{{ event_timestamp }}",
                      "system": "{{ event_system }}",
                      "tags": "{{ event_tags }}",
                      "assigneeaddress": "{{ event_assignee_address }}",
                      "assigneename": "{{ event_assignee_name }}",
                      "artifacts": "{{ event_artifacts }}",
                      "url": "{{ event_url }}"
                    }
                  body_format: json
                  validate_certs: false
                register: homerun_result_message

              - name: Debug the response from homerun
                debug:
                  var: homerun_result_message
            when: send_to_homerun | bool

  - name: users
    play: |
      ---
      - hosts: "{{ target_host | default('all') }}"
        gather_facts: true
        become: true
        vars_files:
          - "{{ path | default('.') }}/{{ profile | default('users') }}.yaml"
        roles:
          - role: sthings.baseos.create_os_user

  - name: tink
    play: |
      ---
      - name: Wait for target machine to be reachable
        hosts: "{{ target_wait_host | default('localhost') }}"
        gather_facts: no
        pre_tasks:
          - name: Include vars
            ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"
            when: path_to_vars_file is defined

        tasks:
          - name: "Pause for {{ pause_time | default(30) }} seconds for machines to be built"
            ansible.builtin.pause:
              minutes: "{{ pause_time | default(30) }}"
            when: pause_time is defined

          - name: Show target IPs
            debug:
              var: groups['all']

          - name: "Wait for SSH (delay: {{ delay_time | default(1) }})"
            ansible.builtin.wait_for:
              host: "{{ item }}"
              port: 22
              delay: "{{ delay_time | default(1) }}"
              timeout: 1200
              sleep: 10
            with_items:
              - "{{ groups['all'] }}"

      - name: Configure target machine
        hosts: "{{ target_host | default('all') }}"
        become: true
        gather_facts: no
        vars_files:
          - "{{ path | default('.') }}/{{ profile | default('tink_u25') }}.yaml"

        roles:
          - role: sthings.baseos.create_os_user

        pre_tasks:
          - name: Include vars
            ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"
            when: path_to_vars_file is defined

        tasks:
          - name: Update all packages
            apt:
              update_cache: yes
              upgrade: "{{ apt_upgrade_type }}"

          - name: Ensure python3-venv is installed
            apt:
              name: "{{ python_venv_package }}"
              state: present

          - name: Create a virtual environment
            command: "python3 -m venv {{ python_venv_path }}"
            args:
              creates: "{{ python_venv_path }}"

          - name: Install required Python modules in venv
            ansible.builtin.pip:
              name: "{{ python_modules }}"
              executable: "{{ python_venv_path }}/bin/pip"

          - name: Set interpreter for later tasks
            set_fact:
              ansible_python_interpreter: "{{ python_venv_path }}/bin/python"

        post_tasks:
          - name: Reboot the machine
            reboot:
              msg: "{{ reboot_message }}"
              pre_reboot_delay: "{{ reboot_pre_delay }}"
              post_reboot_delay: "{{ reboot_post_delay }}"
              reboot_timeout: "{{ reboot_timeout }}"

  - name: uv
    play: |
      ---
      - name: Install UV Python Package Manager
        hosts: "{{ target_host | default('all') }}"
        become: false
        vars:
          uv_version: "0.9.3"
          uv_install_url: "https://github.com/astral-sh/uv/releases/download/{{ uv_version }}/uv-installer.sh"

        pre_tasks:
          - name: Include vars
            ansible.builtin.include_vars: "{{ path_to_vars_file }}.yaml"
            when: path_to_vars_file is defined

        tasks:
          - name: Check if UV is already installed
            command: uv --version
            register: uv_check
            changed_when: false
            failed_when: false

          - name: Download UV installer script
            get_url:
              url: "{{ uv_install_url }}"
              dest: "/tmp/uv-installer.sh"
              mode: '0755'
            when: uv_check.rc != 0

          - name: Install UV
            shell: sh /tmp/uv-installer.sh
            args:
              executable: /bin/sh
            environment:
              SHELL: /bin/sh
            when: uv_check.rc != 0
            register: uv_install

          - name: Remove installer script
            file:
              path: "/tmp/uv-installer.sh"
              state: absent
            when: uv_check.rc != 0

          - name: Verify UV installation
            command: "{{ ansible_env.HOME }}/.local/bin/uv --version"
            register: uv_version_output
            changed_when: false

          - name: Display UV version
            debug:
              msg: "UV installed successfully: {{ uv_version_output.stdout }}"

          - name: Add UV to PATH in .bashrc
            lineinfile:
              path: "{{ ansible_env.HOME }}/.bashrc"
              line: 'export PATH="$HOME/.local/bin:$PATH"'
              state: present
              create: yes
            when: uv_check.rc != 0

          - name: Add UV to PATH in .zshrc (if exists)
            lineinfile:
              path: "{{ ansible_env.HOME }}/.zshrc"
              line: 'export PATH="$HOME/.local/bin:$PATH"'
              state: present
            when:
              - uv_check.rc != 0
              - ansible_env.SHELL is search("zsh")

vars:
  - name: tink_u25
    file: | # pragma: allowlist secret
      ---
      # Package updates
      apt_upgrade_type: dist

      # Connection settings
      target_ip: "{{ target_vm_ip }}"
      target_port: 22
      target_timeout: 300

      # SSH bootstrap settings
      bootstrap_user: tink # pragma: allowlist secret
      bootstrap_password: tink # pragma: allowlist secret
      bootstrap_ssh_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

      # OS settings
      ansible_os_family: Debian
      ansible_become_password: tink # pragma: allowlist secret

      # User creation
      users:
        - username: sthings-tink
          name: sthings-tink user
          ssh_key:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCPTf13fX2gMjlAhXPyJzuf6SJNX4fKiYjplxlJy4MU1V9+hFBqHtVAOwIzA60Z9UP1SAcCD0tUWODS4VVDTVJV3cuX7j7BzKtKyLqD/1Mbs2kPfBPF4cUDqUGCBHO7QLwBD84ib0/muRfYwtTRe++JA246xXDJBHTlcP8MQ6rhs0ku4R94g8WihQxaBZJIJwSDWZIhAD8om3+ai9olBDxdXgFSGFmmSxijSAhW3CKRbOK0nY5IklY6sYH1Y5+Pe7kOEOuO5H5kxYXWxfaPsGNZfRRLZHGEJJli79fCUlR8cg6q71QJYz4jiGDZD+ebgpEYOt2dIkZUyBEv6HpjIb69z7sxDqUAJXdNIR+qW55gsH0ryaeF5MTuigssOOZdMX80CLNygCIVFX3uGZMxDVLImTgkSQmeHJF5nuwKC3tvt59T7H6QP1rQpR4vR/slZsVBS56+1YRdNFqEpRHw8lLhBBdkh/Mndv9Ppbw34/DO/i9o5Hb5B7HOBzxCaGyReOc= andre@TPAEBERT-1"
          groups: ['sudo']
          uid: 1015
          home: /home/sthings-tink
          profile: |
            alias ll='ls -ahl'
          generate_ssh_key: true
          enable_ssh_tcp_forwarding: true

      # Python environment
      python_venv_package: python3-venv
      python_venv_path: /opt/k3s-venv
      python_modules:
        - packaging
        - kubernetes
        - openshift

      # Reboot settings
      reboot_message: "Reboot initiated by Ansible after setup"
      reboot_pre_delay: 5
      reboot_post_delay: 10
      reboot_timeout: 300

      # SSH wait settings
      ssh_wait_timeout: 300
      ssh_wait_sleep: 5
      ssh_wait_delay: 10

  - name: users
    file: |
      ---
      users:
        - username: rke
          name: rke user
          groups: ['{{ admin_group }}']
          uid: 1005
          home: /home/rke
          profile: |
            alias ll='ls -ahl'
          generate_ssh_key: true
          enable_ssh_tcp_forwarding: true
