---
playbooks:
  - name: golang
    play: |
      ---
      - hosts: "{{ target_host | default('localhost') }}"
        environment:
          CONTROLLER_HOST: "{{ controller_host }}"
          CONTROLLER_PASSWORD: "{{ controller_password }}"
          CONTROLLER_USERNAME: "{{ controller_username }}"
          VAULT_APPROLE_ID: "{{ vault_approle_id }}"
          VAULT_APPROLE_SECRET: "{{ vault_approle_secret }}"
          TOWER_VERIFY_SSL: "{{ tower_verify_ssl }}"
          VAULT_URL: "{{ vault_url }}"

        vars:
          config_path: "{{ path | default('.') }}/{{ config_name | default('awx-local-env.yaml') }}"

        vars_files:
          - "{{ config_path }}"
          - "{{ path | default('.') }}/awx-local-env.yaml"
          - "{{ path | default('.') }}/organization-sthings.yaml"
          - "{{ path | default('.') }}/scm-creds-sthings.yaml"
          - "{{ path | default('.') }}/projects-sthings.yaml"
          - "{{ path | default('.') }}/machine-creds-sthings.yaml"
          - "{{ path | default('.') }}/dynamic-inventory-vsphere.yaml"
          - "{{ path | default('.') }}/inventory-source.yaml"
          - "{{ path | default('.') }}/ee-sthings.yaml"
          - "{{ path | default('.') }}/job-golang.yaml"
          - "{{ path | default('.') }}/survey-golang.yaml"

        tasks:
          - ansible.builtin.import_tasks: check_connection.yaml
          - ansible.builtin.import_tasks: render_survey.yaml
          - ansible.builtin.import_tasks: creation_tasks.yaml

vars:
  - name: job-golang
    file: |
      ---
      job_templates:
        stuttgartThings:
          name: install-golang
          organization: stuttgart-things
          inventory: dynamic-inventory-vsphere
          project: stuttgart-things
          playbook: plays/install-golang.yaml
          credentials: sthings-ssh
          executionenv: sthings-ee
          state: present
          ask_verbosity_on_launch: true
          survey_enabled: true
          survey_spec: "{{ lookup('file', 'vars/rendered.json') }}"
